development:
  adapter: postgresql
  encoding: unicode
  database: refinery_database_development
  pool: 5
  username: bemathis
  password:
  min_messages: warning

test:
  adapter: postgresql
  encoding: unicode
  database: refinery_database_test
  pool: 5
  username: bemathis
  password:
  min_messages: warning

production:
  adapter: postgresql
  encoding: unicode
  database: refinery_database_production
  pool: 5
  username: postgres
  password: postgres
  min_messages: warning
